_prefs: 
  baselayer: ''
  saveCenter: true
_properties: {}
attribution: TM2
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -0.12668609619140625
  - 51.50270552998373
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 0
name: Loose leaf
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v4"
styles: 
  - style.mss
  - roads.mss
  - terrain.mss
  - labels.mss
template: ''
